### ISSUE TITLE
In Android, no actions are being triggered in the background.

### ISSUE THREAD

**Issue by safwanidrees** [ChunkyTofuStudios/native_geofence#9]
In iOS, the background trigger functionality is performing as expected; however, it is not functioning correctly on Android.

` await NativeGeofenceManager.instance.initialize();`

` await NativeGeofenceManager.instance.createGeofence(
          Geofence(
            id: id,
            location: Location(
              latitude: center.latitude,
              longitude: center.longitude,
            ),
            radiusMeters: area.calculateRadiusInMeters(),
            triggers: {
              GeofenceEvent.enter,
              GeofenceEvent.exit,
              GeofenceEvent.dwell,
            },
            iosSettings: const IosGeofenceSettings(
              initialTrigger: true,
            ),
            androidSettings: const AndroidGeofenceSettings(
              initialTriggers: {GeofenceEvent.enter},
              expiration: Duration(days: 7),
              loiteringDelay: Duration(minutes: 1),
              notificationResponsiveness: Duration(minutes: 1),
            ),
          ),
          geofenceTriggered,
        );`

**Comment by orkun1675** [comment]
Hi Safwan, thanks for the bug report.

Can you say more about how you are testing this? Have you seen the [Known Issues](https://pub.dev/packages/native_geofence#known-issues) section? Does the example app work for you?

**Comment by safwanidrees** [comment]
Hi, I saw that error.

`E/WM-WorkerWrapper(10453): Work [ id=f534eca3-4d84-4118-8dab-1ebab47a84ba, tags={ com.chunkytofustudios.native_geofence.NativeGeofenceBackgroundWorker } ] failed because it threw an exception/error
E/WM-WorkerWrapper(10453): java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a ListenableWorker to provide an implementation for `getForegroundInfoAsync()`
E/WM-WorkerWrapper(10453):      at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(10453):      at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(10453):      at androidx.work.impl.WorkerWrapper$2.run(WorkerWrapper.java:316)
E/WM-WorkerWrapper(10453):      at androidx.work.impl.utils.SerialExecutorImpl$Task.run(SerialExecutorImpl.java:96)
E/WM-WorkerWrapper(10453):      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/WM-WorkerWrapper(10453):      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/WM-WorkerWrapper(10453):      at java.lang.Thread.run(Thread.java:919)
E/WM-WorkerWrapper(10453): Caused by: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a ListenableWorker to provide an implementation for `getForegroundInfoAsync()`
E/WM-WorkerWrapper(10453):      at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(10453):      at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(10453):      at androidx.work.impl.WorkerWrapper$1.run(WorkerWrapper.java:298)
E/WM-WorkerWrapper(10453):      at android.os.Handler.handleCallback(Handler.java:883)
E/WM-WorkerWrapper(10453):      at android.os.Handler.dispatchMessage(Handler.java:100)
E/WM-WorkerWrapper(10453):      at android.os.Looper.loop(Looper.java:240)
E/WM-WorkerWrapper(10453):      at android.app.ActivityThread.main(ActivityThread.java:7829)
E/WM-WorkerWrapper(10453):      at java.lang.reflect.Method.invoke(Native Method)
E/WM-WorkerWrapper(10453):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:512)
E/WM-WorkerWrapper(10453):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1027)
E/WM-WorkerWrapper(10453): Caused by: java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Expedited WorkRequests require a ListenableWorker to provide an implementation for `getForegroundInfoAsync()`
E/WM-WorkerWrapper(10453):      at androidx.work.impl.utils.futures.AbstractFuture.getDoneValue(AbstractFuture.java:515)
E/WM-WorkerWrapper(10453):      at androidx.work.impl.utils.futures.AbstractFuture.get(AbstractFuture.java:474)
E/WM-WorkerWrapper(10453):      at androidx.work.impl.utils.WorkForegroundRunnable$1.run(WorkForegroundRunnable.java:100)
E/WM-WorkerWrapper(10453):      ... 7 more
E/WM-WorkerWrapper(10453): Caused by: java.lang.IllegalStateException: Expedited WorkRequests require a ListenableWorker to provide an implementation for `getForegroundInfoAsync()`
E/WM-WorkerWrapper(10453):      at androidx.work.ListenableWorker.getForegroundInfoAsync(ListenableWorker.java:259)
E/WM-WorkerWrapper(10453):      at androidx.work.impl.utils.WorkForegroundRunnable.lambda$run$0$androidx-work-impl-utils-WorkForegroundRunnable(WorkForegroundRunnable.java:85)
E/WM-WorkerWrapper(10453):      at androidx.work.impl.utils.WorkForegroundRunnable$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
E/WM-WorkerWrapper(10453):      ... 7 more
I/WM-WorkerWrapper(10453): Worker result FAILURE for Work [ id=f534eca3-4d84-4118-8dab-1ebab47a84ba, tags={ com.chunkytofustudios.native_geofence.NativeGeofenceBackgroundWorker } ]`

**Comment by safwanidrees** [comment]
D/NativeGeofenceBroadcastReceiver(13755): Geofence broadcast received.

I saw that when I changed the location in the real device. But in geofenceTriggered nothing is happening

**Comment by yarith28** [comment]
I believe this is an error that caused on Android 10 and 11. I think I have an idea how to fix it.

**Comment by orkun1675** [comment]
Were you testing on a device running Android 30 or lower?

If so, https://github.com/ChunkyTofuStudios/native_geofence/commit/2f32a254aab602c0319b4af984b62d3aa9d20577 should fix this. Can you give it a try and let me know?

**Comment by orkun1675** [comment]
Version `1.0.7` is released which contains the fix.
